name: Linter & Tests

on:
  push:
    branches: [ master ]
    tags:
      - v*.*.*
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"

    steps:
    - uses: actions/checkout@v4

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.6"
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: Create lock file and install dependencies
      run: |
        uv lock
        uv sync --all-extras --dev
    
    - name: Run checks and tests
      run: |
        uv tool run ruff check .
        uv tool run ruff format --check .
        uv run pytest --cov=smiles_validator tests/