name: 📦 Publish to PyPI

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/smiles-validator
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.6"
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: '**/uv.lock'

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build package
        run: uv build

      - name: Generate changelog
        uses: git-chglog/git-chglog-action@v0.1.1
        id: changelog
        with:
          template: keepachangelog
          latestTag: true
          outputFormat: markdown

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.body }}
