name: Publish to PyPI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check package version
        uses: MathieuMoalic/action-python-package-new-version@v1.0.1

      - name: Install uv
        if: env.NEW_VERSION == 'true'
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.6"
          python-version: "3.10"
          enable-cache: true

      - name: Install dependencies
        if: env.NEW_VERSION == 'true'
        run: uv sync --locked --all-extras --dev

      - name: Build package
        if: env.NEW_VERSION == 'true'
        run: uv build

      - name: Publish package distributions to PyPI
        if: env.NEW_VERSION == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
