name: Release & Publish (PyPI)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    name: Create Release and Publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/smiles-validator
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.6"
          python-version: "3.12"
          enable-cache: true

      - name: Clean build directory
        run: |
          rm -rf dist/ build/ .uv/ uv.lock

      - name: Create lock file
        run: uv lock

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build package
        run: uv build

      - name: Create GitHub Release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "PyPI release: https://pypi.org/project/smiles-validator/"
          draft: false
          prerelease: false

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
