name: 📦 Release & Publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/smiles-validator
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.6"
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: '**/uv.lock'

      - name: Create uv.lock
        run: uv lock

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build package
        run: uv build

      - name: Generate changelog
        id: changelog
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0)
          
          # Generate changelog
          echo "## [${{ github.ref_name }}](${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}) ($(date +%Y-%m-%d))" > changelog.md
          echo "" >> changelog.md
          echo "### Changes" >> changelog.md
          echo "" >> changelog.md
          
          # Get commits between tags
          git log --pretty=format:'- %s (%h)' $PREV_TAG..${{ github.ref_name }} >> changelog.md
          
          # Add PyPI link
          echo "" >> changelog.md
          echo "Published to PyPI: https://pypi.org/project/smiles-validator/${{ github.ref_name }}/" >> changelog.md
          
          # Set output
          BODY=$(cat changelog.md | tr -d '\n' | sed 's/\s\+/ /g')
          echo "body=$BODY" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.body }}
          draft: false
          prerelease: false
